export const data = [
  {
    badgeId: 1,
    badgeName: "첫 만남",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_first+step.png",
    badgeType: "ATTENDANCE",
    badgeDescription: "처음 가입",
    operator: ">=",
    value: "1",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 2,
    badgeName: "가치를 새기다",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_mark+the+moment.png",
    badgeType: "LOG",
    badgeDescription: "처음 가계부 작성",
    operator: ">=",
    value: "1",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 3,
    badgeName: "기록의 씨앗",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_seed+of+records.png",
    badgeType: "LOG",
    badgeDescription: "가계부에 기록10번",
    operator: ">=",
    value: "10",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 4,
    badgeName: "연속 출석자",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_daily+streak.png",
    badgeType: "CONSECUTIVE_ATTENDANCE",
    badgeDescription: "3일 이상 연속 출석",
    operator: ">=",
    value: "3",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 5,
    badgeName: "절약의 시작",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_saving+start.png",
    badgeType: "MONEY",
    badgeDescription: "만원 이상 절약",
    operator: ">=",
    value: "10000",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 6,
    badgeName: "프로 출석러",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_streak+master.png",
    badgeType: "ATTENDANCE",
    badgeDescription: "출석 (연속xx) 10회 이상 달성",
    operator: ">=",
    value: "10",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 7,
    badgeName: "한 푼 두 푼",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_penny+saver.png",
    badgeType: "MONEY",
    badgeDescription: "총 절약 금액이 5만원 이상 달성",
    operator: ">=",
    value: "50000",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 8,
    badgeName: "꾸준함이 매력",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_stay+steady.png",
    badgeType: "ATTENDANCE",
    badgeDescription: "출석 (연속xx) 50번 이상",
    operator: ">=",
    value: "50",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 9,
    badgeName: "기록의 불꽃",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_record+blaze.png",
    badgeType: "LOG",
    badgeDescription: "기록 100회 이상",
    operator: ">=",
    value: "100",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
  {
    badgeId: 10,
    badgeName: "채움의 달인",
    emblemPath:
      "https://zerocost-image-bucket.s3.ap-northeast-2.amazonaws.com/badge_image/badge_savings+pro.png",
    badgeType: "MONEY",
    badgeDescription: "총 절약 금액 100만원 이상",
    operator: ">=",
    value: "100",
    count: 0,
    rgstId: 3,
    rgstDt: "2024-11-30 20:54:05",
    updtId: 3,
    updtDt: "2024-11-30 20:54:05",
    acquireYN: "N",
  },
];
